CREATE TABLE IF NOT EXISTS admin_action_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_email TEXT NOT NULL,
  action TEXT NOT NULL,
  target_table TEXT NOT NULL,
  target_id TEXT NOT NULL,
  before_state JSONB,
  after_state JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE admin_action_log ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_admin_action_log_created_at
  ON admin_action_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_action_log_target
  ON admin_action_log (target_table, target_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_action_log_actor
  ON admin_action_log (actor_email, created_at DESC);

GRANT SELECT, INSERT ON admin_action_log TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'admin_action_log'
      AND policyname = 'content admin can read audit log'
  ) THEN
    CREATE POLICY "content admin can read audit log"
      ON admin_action_log
      FOR SELECT
      TO authenticated
      USING (is_content_admin());
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'admin_action_log'
      AND policyname = 'content admin can insert audit log'
  ) THEN
    CREATE POLICY "content admin can insert audit log"
      ON admin_action_log
      FOR INSERT
      TO authenticated
      WITH CHECK (
        is_content_admin()
        AND lower(actor_email) = lower(auth.jwt() ->> 'email')
      );
  END IF;
END
$$;
