plugins {
    id 'com.android.application' version '8.11.0'
}

android {
    namespace 'com.bathtimestudio.bathtime.pockettest'
    compileSdk 36

    defaultConfig {
        applicationId 'com.bathtimestudio.bathtime.pockettest'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
