import { StyleSheet } from 'react-native';
import {
  APP_BG_BASE,
  CARD_BORDER,
  CARD_SHADOW,
  CARD_SURFACE,
  PILL_ACTIVE_BG,
  PILL_BG,
  PILL_BORDER,
  TEXT_PRIMARY,
  TYPE_BODY,
  TYPE_HEADING_MD,
  TYPE_TITLE,
  V2_ACCENT,
  V2_ACCENT_SOFT,
  V2_ACCENT_TEXT,
  V2_BG_BASE,
  V2_BORDER,
  V2_SHADOW,
  V2_SURFACE,
  V2_TEXT_MUTED,
  V2_TEXT_PRIMARY,
  V2_TEXT_SECONDARY,
} from '@/src/data/colors';

export const ui = StyleSheet.create({
  screenShell: {
    flex: 1,
    backgroundColor: APP_BG_BASE,
  },
  glassCard: {
    backgroundColor: CARD_SURFACE,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 18,
    shadowColor: CARD_SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: TYPE_TITLE,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
  titleHero: {
    fontSize: TYPE_HEADING_MD,
    fontWeight: '800',
    color: TEXT_PRIMARY,
    letterSpacing: 0.2,
  },
  bodyText: {
    fontSize: TYPE_BODY,
    color: TEXT_PRIMARY,
  },
  pillButton: {
    backgroundColor: PILL_BG,
    borderWidth: 1,
    borderColor: PILL_BORDER,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  pillButtonActive: {
    backgroundColor: PILL_ACTIVE_BG,
    borderColor: PILL_BORDER,
  },
  tabBarStyle: {
    backgroundColor: 'rgba(10, 24, 55, 0.98)',
    borderTopColor: 'rgba(132, 152, 188, 0.24)',
    borderTopWidth: 1,
    height: 76,
    paddingTop: 8,
    paddingBottom: 8,
  },
  screenShellV2: {
    flex: 1,
    backgroundColor: V2_BG_BASE,
  },
  glassCardV2: {
    backgroundColor: V2_SURFACE,
    borderWidth: 1,
    borderColor: V2_BORDER,
    borderRadius: 18,
    shadowColor: V2_SHADOW,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 4,
  },
  titleHeroV2: {
    fontSize: TYPE_HEADING_MD,
    fontWeight: '800',
    color: V2_TEXT_PRIMARY,
    letterSpacing: 0.2,
  },
  sectionTitleV2: {
    fontSize: TYPE_TITLE,
    fontWeight: '700',
    color: V2_TEXT_PRIMARY,
  },
  bodyTextV2: {
    fontSize: TYPE_BODY,
    color: V2_TEXT_SECONDARY,
  },
  captionTextV2: {
    fontSize: TYPE_BODY - 2,
    color: V2_TEXT_MUTED,
  },
  pillButtonV2: {
    backgroundColor: V2_SURFACE,
    borderWidth: 1,
    borderColor: V2_BORDER,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  pillButtonV2Active: {
    backgroundColor: V2_ACCENT_SOFT,
    borderColor: V2_ACCENT,
  },
  primaryButtonV2: {
    backgroundColor: V2_ACCENT,
    borderRadius: 16,
    minHeight: 54,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonTextV2: {
    color: V2_ACCENT_TEXT,
    fontSize: TYPE_BODY,
    fontWeight: '800',
  },
  secondaryButtonV2: {
    backgroundColor: V2_SURFACE,
    borderRadius: 16,
    minHeight: 54,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: V2_BORDER,
  },
  secondaryButtonTextV2: {
    color: V2_TEXT_PRIMARY,
    fontSize: TYPE_BODY,
    fontWeight: '700',
  },
});
