import { Platform, StyleSheet } from 'react-native';
import {
  TYPE_SCALE,
  V2_ACCENT,
  V2_ACCENT_SOFT,
  V2_ACCENT_TEXT,
  V2_BG_BASE,
  V2_BORDER,
  V2_BORDER_STRONG,
  V2_PILL_ACTIVE_BG,
  V2_PILL_BG,
  V2_PILL_BORDER,
  V2_SHADOW,
  V2_SURFACE,
  V2_TEXT_PRIMARY,
  V2_TEXT_SECONDARY,
  V2_TEXT_MUTED,
} from '@/src/data/colors';
import { luxuryFonts, luxuryRadii } from '@/src/theme/luxury';

export const ui = StyleSheet.create({
  screenShell: {
    flex: 1,
    backgroundColor: V2_BG_BASE,
  },
  glassCard: {
    backgroundColor: V2_SURFACE,
    borderWidth: 1,
    borderColor: V2_BORDER,
    borderRadius: luxuryRadii.card,
    ...Platform.select({
      web: {
        boxShadow: `0px 18px 36px ${V2_SHADOW}`,
      },
      default: {
        shadowColor: V2_SHADOW,
        shadowOffset: { width: 0, height: 14 },
        shadowOpacity: 1,
        shadowRadius: 28,
        elevation: 8,
      },
    }),
  },
  sectionTitle: {
    fontSize: TYPE_SCALE.title,
    fontFamily: luxuryFonts.display,
    color: V2_TEXT_PRIMARY,
  },
  titleHero: {
    fontSize: TYPE_SCALE.headingMd,
    fontFamily: luxuryFonts.display,
    color: V2_TEXT_PRIMARY,
    letterSpacing: 0.2,
  },
  bodyText: {
    fontSize: TYPE_SCALE.body,
    color: V2_TEXT_SECONDARY,
    fontFamily: luxuryFonts.sans,
  },
  pillButton: {
    backgroundColor: V2_PILL_BG,
    borderWidth: 1,
    borderColor: V2_PILL_BORDER,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  pillButtonActive: {
    backgroundColor: V2_PILL_ACTIVE_BG,
    borderColor: V2_ACCENT,
  },
  tabBarStyle: {
    backgroundColor: 'rgba(12, 19, 25, 0.98)',
    borderTopColor: V2_BORDER,
    borderTopWidth: 1,
    height: 82,
    paddingTop: 10,
    paddingBottom: 10,
  },
  screenShellV2: {
    flex: 1,
    backgroundColor: V2_BG_BASE,
  },
  glassCardV2: {
    backgroundColor: V2_SURFACE,
    borderWidth: 1,
    borderColor: V2_BORDER,
    borderRadius: luxuryRadii.card,
    ...Platform.select({
      web: {
        boxShadow: `0px 18px 36px ${V2_SHADOW}`,
      },
      default: {
        shadowColor: V2_SHADOW,
        shadowOffset: { width: 0, height: 14 },
        shadowOpacity: 1,
        shadowRadius: 28,
        elevation: 8,
      },
    }),
  },
  titleHeroV2: {
    fontSize: TYPE_SCALE.headingMd,
    fontFamily: luxuryFonts.display,
    color: V2_TEXT_PRIMARY,
    letterSpacing: 0.2,
  },
  sectionTitleV2: {
    fontSize: TYPE_SCALE.title,
    fontFamily: luxuryFonts.display,
    color: V2_TEXT_PRIMARY,
  },
  bodyTextV2: {
    fontSize: TYPE_SCALE.body,
    color: V2_TEXT_SECONDARY,
    fontFamily: luxuryFonts.sans,
  },
  captionTextV2: {
    fontSize: TYPE_SCALE.caption,
    color: V2_TEXT_MUTED,
    fontFamily: luxuryFonts.sans,
  },
  pillButtonV2: {
    backgroundColor: V2_PILL_BG,
    borderWidth: 1,
    borderColor: V2_PILL_BORDER,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  pillButtonV2Active: {
    backgroundColor: V2_PILL_ACTIVE_BG,
    borderColor: V2_ACCENT,
  },
  primaryButtonV2: {
    backgroundColor: V2_ACCENT,
    borderRadius: luxuryRadii.button,
    minHeight: 56,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: V2_BORDER_STRONG,
  },
  primaryButtonTextV2: {
    color: V2_ACCENT_TEXT,
    fontSize: TYPE_SCALE.body,
    fontWeight: '800',
    fontFamily: luxuryFonts.sans,
    letterSpacing: 0.2,
  },
  secondaryButtonV2: {
    backgroundColor: V2_SURFACE,
    borderRadius: luxuryRadii.button,
    minHeight: 56,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: V2_BORDER,
  },
  secondaryButtonTextV2: {
    color: V2_TEXT_PRIMARY,
    fontSize: TYPE_SCALE.body,
    fontWeight: '700',
    fontFamily: luxuryFonts.sans,
    letterSpacing: 0.2,
  },
});
