export const copy = {
  home: {
    title: '오늘의 맞춤 목욕',
    subtitlePrefix: '오늘 상태:',
    modeHint: {
      sleep: '케어(몸 상태에 맞춘 루틴) · 수면 준비 중심',
      recovery: '케어(몸 상태에 맞춘 루틴) · 회복 중심',
      reset: '케어(몸 상태에 맞춘 루틴) · 전환 중심',
    },
    lateNightBadge: '늦은 시간이라 수면 준비 루틴을 먼저 보여드려요.',
    conflictBadge: '조건이 겹쳐서 가장 안전한 루틴 1개를 먼저 추천해요.',
    sections: {
      signal: '오늘 상태',
      environment: '목욕 환경',
      tripTheme: '트립 테마',
      suggestions: '지금 추천 루틴',
      quickActions: '빠른 메뉴',
    },
    actions: {
      quickStart: '바로 시작',
      viewHistory: '기록 보기',
      changeEnvironment: '환경 바꾸기',
    },
    rankLabel: {
      primary: '가장 먼저 추천해요',
      secondary_1: '함께 고려해보세요',
      secondary_2: '가벼운 대안이에요',
    },
    resetSafeHint: '냉수 단계는 안전을 위해 자동으로 제외됐어요.',
    noCommerceNotice: '지금은 상품 대신 루틴부터 바로 시작할 수 있어요.',
    beginnerGuide: '처음 시작이라 안전하고 무난한 기본 추천부터 보여드려요.',
    safetyPriorityBadge: '안전 우선 적용',
    streakTitle: '이번주 루틴',
    todayDone: '오늘 루틴 완료',
    todayPending: '오늘 루틴 미완료',
    weeklyCount: (count: number, goal: number) => `이번주 ${count} / ${goal}회`,
    dailyStreak: (days: number) => `${days}일 연속`,
    weeklyStreak: (weeks: number) => `${weeks}주 연속`,
  },
  suggestion: {
    titleCare: '추천 루틴 자세히 보기',
    titleTrip: '트립 루틴 자세히 보기',
    labels: {
      state: '현재 상태',
      narrative: '오늘의 분위기',
      atmosphere: '이런 느낌으로 진행돼요',
      why: '이렇게 추천한 이유',
      params: '진행 방법',
      goal: '기대할 수 있는 변화',
      alternative: '다른 선택',
    },
    cta: {
      close: '닫기',
      start: '이 루틴 시작하기',
    },
  },
  product: {
    title: '준비물로 볼 제품',
    subtitle: '이번 루틴 준비물 카테고리 안에서 고르기 쉬운 제품이에요',
    slotTitle: {
      A: '대표 준비물',
      B: '비슷한 대안',
      C: '다른 선택지',
    },
    pickBadge: '추천 픽',
    labels: {
      mechanism: '추천 이유',
      priceTier: '가격대',
    },
    cta: {
      detail: '제품 보기',
      purchase: '구매 링크',
      close: '닫기',
      continue: '루틴 계속하기',
    },
  },
  routine: {
    stepPrep: '준비',
    stepRun: '진행',
    stepFinish: '마무리',
    preBath: {
      title: '시작 전 꼭 확인하세요',
      subtitle: '안전 제약이 걸린 루틴입니다. 핵심 주의사항만 확인하고 시작해주세요.',
      historySubtitle:
        '이전에 저장한 루틴입니다. 오늘도 같은 제약을 지킬 수 있는지 확인한 뒤 다시 시작해주세요.',
      warningBadge: '주의',
      warningLead: '이번 루틴은 안전 제약이 있어요',
      reviewCta: '주의사항 확인하기',
      historyReviewCta: '다시 시작 전 확인하기',
      historyStartCta: '다시 시작하기',
    },
    introLead: '준비가 되셨다면, 깊게 숨을 한 번 내쉬어보세요.',
    introHint: '화면을 터치하면 바로 시작합니다',
    timerPaused: '잠시 멈춤',
    timerPause: '일시정지',
    timerResume: '다시 시작',
    timerFinish: '끝내기',
    safetyTitle: '안전 안내',
    safetyLines: [
      '38~40°C를 권장해요. 수면 루틴은 38~41°C예요.',
      '10~15분 진행하고 이상하면 바로 중단하세요.',
      '음주 직후에는 사용하지 마세요.',
    ],
    evidence: {
      title: '추천 근거',
      defaultSafety: '권장 수온과 시간을 지키고, 불편하면 바로 중단하세요.',
      reasonTemplates: {
        trip: (themeTitle: string) => `${themeTitle} 테마 기반 트립 루틴으로 구성했어요.`,
        care: (personaLabel: string) => `${personaLabel} 기준으로 현재 상태에 맞췄어요.`,
        params: (bathTypeLabel: string, temperature: number, durationLabel: string) =>
          `${bathTypeLabel} 기준 ${temperature}°C · ${durationLabel}으로 최적화했어요.`,
      },
    },
    checklist: {
      title: '안전 체크리스트',
      fallback: [
        '권장 수온과 시간을 다시 확인하세요.',
        '불편하면 즉시 중단하고 휴식하세요.',
      ],
    },
    recipe: {
      tripModeLabel: '트립 · 분위기 전환 루틴',
      careModeLabel: '케어 · 몸 상태에 맞춘 루틴',
      summaryEyebrow: '루틴 요약',
      summaryTitle: '이번 루틴은 이렇게 진행돼요',
      prepTitle: '시작 전에 이렇게 준비하세요',
      prepSubtitle: '루틴의 핵심만 먼저 읽고 바로 시작할 수 있게 정리했어요',
      guideTitle: '오늘의 휴식을 위한 준비',
      guideSubtitle: '온전한 휴식을 위해 필요한 것만 가볍게 안내해드려요.',
      requiredLabel: '지금 있으면 되는 것',
      optionalLabel: '더하면 좋은 선택',
      noneTitle: '없음',
      showerOptionalTitle: '바디워시 또는 샤워타월',
      noOptionalTitle: '추가 준비물 없음',
      requiredBody: (name: string) => `${name} 하나만 있으면 충분해요.`,
      showerNoRequiredBody: '새로 사지 않아도 괜찮아요. 집에 있는 바디워시나 샤워타월 정도면 시작할 수 있어요.',
      noRequiredBody: '다른 준비물 없이도 충분해요. 몸과 마음만 가볍게 쉬러 오시면 돼요.',
      optionalBody: (name: string) => `${name} 대신 고르거나 함께 보기 좋은 완제품이에요.`,
      showerOptionalBody: '향이 있는 바디워시나 샤워타월 정도만 더해도 충분해요.',
      noOptionalBody: '이번 루틴은 추가 준비물 없이도 충분해요.',
      waterStepLabel: '물 준비',
      ingredientStepLabel: '재료 넣기',
      ingredientStepBody: (name: string) => `${name} 하나만 준비하면 바로 시작할 수 있어요.`,
      noIngredientStepBody: '필수 준비물 없이도 괜찮아요. 집에 있는 것만으로 먼저 시작해보세요.',
      bridgeEyebrow: '소믈리에의 제안',
      bridgeTitle: '오늘의 분위기에 어울리는 제품',
      bridgeBody: '이 루틴의 결을 해치지 않으면서, 휴식의 밀도를 조금 더 높여줄 제품만 골랐어요.',
      bridgeButton: '추천 제품 보기',
      safetyEyebrow: '안전 먼저',
      bathLabel: '입욕',
      temperatureLabel: '수온',
      durationLabel: '시간',
      environmentLabel: '환경',
      sleepWindow: {
        eyebrow: '수면 준비 타이밍',
        title: '잠들기 90분 전까지 끝내는 편이 좋아요',
        defaultBedtimeHint: '기본 취침 시각 23:00 기준',
        scheduledSummary: (startTime: string, endTime: string) =>
          `${startTime}쯤 시작해 ${endTime} 전에 마치는 흐름을 추천해요.`,
        startNowSummary: (bedtimeTime: string) =>
          `지금 시작한다면 루틴이 끝난 뒤 최소 90분은 쉬고 ${bedtimeTime} 이후에 잠자리에 들어보세요.`,
      },
    },
    startCta: '목욕 시작하기',
  },
  careCards: {
    featuredEyebrow: '먼저 보면 좋아요',
    quickEyebrow: '빠르게 시작하기',
    disabledFooter: '환경 조건 먼저 보기',
    defaultFooter: '세부 방식 고르기',
    placeholderSubtitle: '곧 추가될 예정이에요',
    placeholderDisabled: '준비 중이에요',
    restrictedDisabled: '현재 환경에선 제한적으로 추천돼요',
    hangoverBlocked: '숙취 루틴은 전신 입욕 없이 미지근한 족욕만 가능해요.',
    edemaBlocked: '붓기 루틴은 샤워보다 욕조나 부분입욕을 먼저 권장해요.',
    sensitiveSkinBadge: '저자극 조정',
    sensitiveSkinAdjusted: '저자극 기준으로 자동 조정해요.',
  },
  completion: {
    feedbackTitleDefault: '오늘 루틴은 어떠셨나요?',
    feedbackTitleWithThemePrefix: '오늘의',
    feedbackTitleWithThemeSuffix: '분위기는 어떠셨나요?',
    summaryTitle: '이번 루틴을 이렇게 정리했어요',
    feedback: {
      good: '좋아요',
      bad: '별로예요',
      thanks: '의견 고마워요. 다음 추천에 반영할게요.',
    },
    monthlyPrefix: '이번 달',
    monthlySuffix: '번째 루틴을 완료했어요',
    memoryTitle: '이번 기록 요약',
    memoryLabels: {
      snapshot: '진행 기록',
      weight: '선호도 변화',
      recall: '오늘의 한 줄 기억',
    },
    aftercare: {
      eyebrow: '끝난 직후',
      title: '지금 바로 이 세 가지만 챙겨주세요',
      items: [
        '물 한 잔으로 수분을 먼저 보충하세요.',
        '물기가 완전히 마르기 전에 보습제를 가볍게 발라주세요.',
        '어지럽거나 심장이 빨리 뛰면 바로 앉아서 쉬세요.',
      ],
    },
    homeCta: '홈으로 가기',
    loading: '불러오는 중이에요...',
  },
  history: {
    title: '기록 요약',
    expand: '펼치기',
    collapse: '접기',
    summary: {
      sessions: '총 루틴',
      care: '케어',
      trip: '트립',
      avgDuration: '평균 진행 시간',
      topEnvironment: '가장 자주 쓴 환경',
      memoryCount: '누적 기록 수',
      topTheme: '자주 선택한 테마',
      noTheme: '아직 테마 기록이 없어요.',
      noData: '데이터를 모으는 중이에요.',
    },
    recallTitlePrefix: '최근 기억',
    cardLabels: {
      environmentPrefix: '환경:',
      weightPrefix: '선호도:',
      modeCare: '케어',
      modeTrip: '트립',
      defaultTitle: '맞춤 케어',
    },
    empty: {
      title: '아직 기록이 없어요',
      subtitle: '첫 루틴을 시작하면 여기에 쌓여요.',
    },
  },
  settings: {
    sectionProfile: '내 정보',
    sectionActions: '설정',
    sectionApp: '앱 정보',
    environmentLabel: '목욕 환경',
    healthLabel: '건강 상태',
    versionLabel: '버전',
    nameLabel: '이름',
    resetProfile: '프로필 다시 설정하기',
    resetDialogTitle: '프로필 초기화',
    resetDialogBody:
      '프로필을 초기화하면 처음부터 다시 설정해야 해요. 계속할까요?',
    resetCancel: '취소',
    resetConfirm: '초기화',
    resetErrorTitle: '오류',
    resetErrorBody: '프로필 초기화 중 문제가 발생했어요. 다시 시도해주세요.',
    loading: '불러오는 중이에요...',
  },
  alerts: {
    purchaseUnavailableTitle: '구매 링크 없음',
    purchaseUnavailableBody: '아직 연결된 구매 링크가 없어요.',
    openLinkFailedTitle: '링크 열기 실패',
    openLinkFailedBody: '지금은 구매 링크를 열 수 없어요.',
    finishRoutineTitle: '루틴 종료',
    finishRoutineBody: '지금 끝내면 현재 진행 상태로 루틴이 종료됩니다. 계속할까요?',
    cancel: '취소',
    proceed: '진행',
    finish: '종료',
  },
  disclosure: {
    title: '안내',
    baseLines: [
      'BathSommelier는 의료 진단이나 치료를 하지 않습니다.',
      '건강 상태가 걱정되면 전문가와 먼저 상담하세요.',
    ],
    coldWarning:
      '고혈압·부정맥·뇌혈관 병력이 있으면 냉수 단계는 피하세요.',
    safeOnly:
      '현재 상태에서는 안전 루틴만 보여드려요. 이상하면 즉시 중단하세요.',
    conflictResolved: '조건이 겹칠 때는 더 안전한 추천을 먼저 보여드려요.',
    diabetesCaution:
      '당뇨가 있으면 온도 체감이 다를 수 있어 천천히 진행하세요.',
  },
} as const;
