import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import ts from 'typescript';

const rootDir = path.resolve(new URL('..', import.meta.url).pathname);
const seedSourcePath = path.join(rootDir, 'src', 'data', 'catalogResearchSeed.ts');
const outputDir = path.join(rootDir, 'output');
const jsonOutputPath = path.join(outputDir, 'catalog-research-seed.v1.json');
const sqlOutputPath = path.join(outputDir, 'catalog-research-seed.v1.inserts.sql');

function escapeSqlString(value) {
  return String(value).replace(/'/g, "''");
}

function toSqlValue(value) {
  if (value === undefined || value === null) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'boolean') return value ? '1' : '0';
  if (Array.isArray(value)) return `'${escapeSqlString(JSON.stringify(value))}'`;
  return `'${escapeSqlString(value)}'`;
}

function buildInsertStatement(tableName, row) {
  const columns = Object.keys(row);
  const values = columns.map((column) => toSqlValue(row[column]));
  return `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES (${values.join(', ')});`;
}

async function loadSeedModule() {
  const source = await readFile(seedSourcePath, 'utf8');
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  }).outputText;

  const module = { exports: {} };
  const context = vm.createContext({
    module,
    exports: module.exports,
    console,
  });

  new vm.Script(transpiled, { filename: 'catalogResearchSeed.transpiled.js' }).runInContext(
    context
  );

  return module.exports;
}

async function main() {
  const seedModule = await loadSeedModule();
  const canonicalProducts = seedModule.CANONICAL_PRODUCT_SEED_V1;
  const marketListings = seedModule.PRODUCT_MARKET_LISTING_SEED_V1;
  const matchRules = seedModule.PRODUCT_MATCH_RULE_SEED_V1;
  const snapshotDate = seedModule.PRODUCT_RESEARCH_SNAPSHOT_DATE;

  const payload = {
    snapshotDate,
    canonicalProducts,
    marketListings,
    matchRules,
    counts: {
      canonicalProducts: canonicalProducts.length,
      marketListings: marketListings.length,
      matchRules: matchRules.length,
    },
  };

  const sqlLines = [
    '-- Generated by scripts/export_catalog_research_seed.mjs',
    `-- Snapshot date: ${snapshotDate}`,
    'BEGIN TRANSACTION;',
    ...canonicalProducts.map((item) =>
      buildInsertStatement('canonical_product', {
        id: item.id,
        ingredient_key: item.ingredientKey,
        name_ko: item.nameKo,
        brand: item.brand,
        category: item.category,
        mechanism: item.mechanism,
        price_tier: item.priceTier,
        environments_json: JSON.stringify(item.environments),
        summary: item.summary,
        editorial_eyebrow: item.editorialEyebrow,
        editorial_footer_hint: item.editorialFooterHint,
        status: item.status,
        last_verified_at: item.lastVerifiedAt,
      })
    ),
    ...marketListings.map((item) =>
      buildInsertStatement('product_market_listing', {
        id: item.id,
        canonical_product_id: item.canonicalProductId,
        market: item.market,
        source_url: item.sourceUrl,
        title_snapshot: item.titleSnapshot,
        seller_snapshot: item.sellerSnapshot ?? null,
        price_snapshot_krw: item.priceSnapshotKrw ?? null,
        availability: item.availability,
        verified_at: item.verifiedAt,
        source_confidence: item.sourceConfidence,
        notes: item.notes ?? null,
      })
    ),
    ...matchRules.map((item) =>
      buildInsertStatement('product_match_rule', {
        id: item.id,
        canonical_product_id: item.canonicalProductId,
        ingredient_keys_json: JSON.stringify(item.ingredientKeys),
        allowed_environments_json: JSON.stringify(item.allowedEnvironments),
        mode_bias_json: item.modeBias ? JSON.stringify(item.modeBias) : null,
        priority_weight: item.priorityWeight,
        is_sommelier_pick_candidate: item.isSommelierPickCandidate,
        status: item.status,
      })
    ),
    'COMMIT;',
    '',
  ];

  await mkdir(outputDir, { recursive: true });
  await writeFile(jsonOutputPath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
  await writeFile(sqlOutputPath, sqlLines.join('\n'), 'utf8');

  console.log(
    JSON.stringify(
      {
        snapshotDate,
        jsonOutputPath,
        sqlOutputPath,
        counts: payload.counts,
      },
      null,
      2
    )
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
